---
- name: Build and Deploy an Docker Container
  hosts: all 
  
  pre_tasks:

  - name: Login into Red Hat Registry 
    docker_login:
      registry: registry.redhat.io
      username: pbernal@compusoluciones.com
      password: Alejandra+240496
      email: pbernal@compusoluciones.com

  - name: Build an Docker Image
    docker_image:
      build:
        path: /git-webapp
      name: "{{ image_container }}"
      source: build

  tasks:

  - name: Build Container from Image
    docker_container:
      name: "{{ name_container }}{{ item }}"
      image: "{{ image_container }}"
      state: started
    with_sequence: count="{{ num_of_container }}"
